export const capitalizeFirst = (value: string): string => {
    if (!value) return '';
    return value.charAt(0).toUpperCase() + value.slice(1);
  };
  
  export const staticProducts:any = [
  {
    id: 1,
    title: "Smart TV",
    price: 299.99,
    description: "A 50-inch smart TV with 4K resolution.",
    category: "tv",
    image: "/products/smart-tv.png",
    brand: "Onida",
    model: "widerX",
    color: "black",
    discount: 20,

  },
  {
    id: 2,
    title: "Wireless Headphones",
    price: 99.99,
    description: "Noise cancelling over-ear headphones.",
    category: "audio",
    image: "/products/headphone.png",
    brand: "JBL",
    model: "curve-bend",
    color: "Black",
  },
  {
    id: 3,
    title: "Gaming Laptop",
    price: 1299.99,
    description: "High performance laptop for gaming and work.",
    category: "laptop",
    image: "/products/laptop.png",
    brand: "Lenova",
    model: "speedX20",
    color: "steel",
    discount: 15,
  },
  {
    id: 4,
    title: "Smartphone Y20",
    price: 699.99,
    description: "Latest smartphone with AMOLED display.",
    category: "mobile",
    image: "/products/smartphone.png",
    brand: "Xamio",
    model: "k23",
    color: "black",
    discount: 33,
  },
    {
    id: 5,
    title: "Wireless Mouse",
    price: 49.99,
    description: "Ergonomic wireless mouse with fast response.",
    category: "gaming",
    image: "/products/wireless-mouse.png",
    brand: "Logitech",
    model: "M185",
    color: "Black",
    discount: 10,
  },
  {
    id: 6,
    title: "Sound Box",
    price: 149.99,
    description: "Powerful portable sound box with deep bass.",
    category: "appliances",
    image: "/products/sound-box.png",
        brand: "Sony",
    model: "XB33",
    color: "Blue",
    discount: 15,
  },
   {
    id: 7,
    title: "VR Headset",
    price: 399.99,
    description: "Immersive VR headset for gaming and entertainment.",
    category: "gaming",
    brand: "ImmersiTech",
    model: "VRX-1",
    color: "Black",
    image: "/products/vr.png",
    discount: 10,
  },
  {
    id: 8,
    title: "Smart Watch",
    price: 199.99,
    description: "Feature-packed smartwatch with fitness tracking.",
    category: "electronics",
    brand: "TimeFit",
    model: "SF-100",
    color: "Blue",
    image: "/products/smart-watch.png",
  },
  {
    id: 9,
    title: "Gaming Laptop Pro",
    price: 1599.99,
    description: "Ultimate gaming laptop with RGB keyboard and 4K screen.",
    category: "laptop",
    brand: "GamerTech",
    model: "GTX-Pro-21",
    color: "Black",
    image: "/products/laptop2.png",
    discount: 20,
  },
  {
  id: 10,
  title: "Curve TV",
  price: 799.99,
  description: "55-inch curved Smart TV with immersive viewing experience.",
  category: "electronics",
  brand: "ViewPro",
  model: "VP-55CURVE",
  color: "Black",
  image: "/products/curve-tv.png",
  discount: 12,
},
];